"""add pdf_path to resume

Revision ID: 3ccaa5ea3b4a
Revises: 8f5f295b6215
Create Date: 2026-07-29 09:12:27.120172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccaa5ea3b4a'
down_revision = '8f5f295b6215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_materials')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('pdf_path')

    op.create_table('study_materials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subcategory', sa.VARCHAR(length=100), nullable=True),
    sa.Column('source_file', sa.VARCHAR(length=200), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('is_learned', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
