"""add company salary, application offer_status, interview_feedback, timeline end_date, resume

Revision ID: 8f5f295b6215
Revises: 
Create Date: 2026-07-25 20:24:56.608625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5f295b6215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer', sa.String(length=100), nullable=True),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('round', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('improvement', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_priority'), ['priority'], unique=False)

    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_priority'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('offer_status')

    op.drop_table('interview_feedbacks')
    op.drop_table('resumes')
    # ### end Alembic commands ###
